
# Unifits/unifits-github-actions/container-image-sign
# Signs a container image (prefer repo@digest) with Cosign (keyless OIDC)
# and optionally attests an SBOM (CycloneDX/SPDX) and a CVE report (e.g., Trivy JSON).

name: "Container Image Sign"
description: "Cosign keyless sign to GAR + optional SBOM/CVE attestations."
branding:
  color: "purple"
  icon: "shield"

inputs:
  image:
    description: "Image reference (use repo@digest)."
    required: true

  # ---- Cosign/registry options ----
  recursive-sign:
    description: "If 'true', add --recursive to sign multi-arch index & images."
    required: false
    default: "false"
  tlog-upload:
    description: "Upload signatures/attestations to Rekor transparency log."
    required: false
    default: "false"
  rekor-url:
    description: "Optional Rekor URL for private instances."
    required: false
    default: ""

  # ---- Optional extra annotations on signature (key=value lines) ----
  extra-annotations:
    description: "Additional --annotation entries (newline-separated 'key=value')."
    required: false
    default: ""

  # ---- CVE report (e.g., Trivy JSON) ----
  cve-report:
    description: "Optional vulnerability report file (e.g., Trivy JSON)."
    required: false
    default: ""
  attest-cve-report:
    description: "If 'true', create a cosign attestation for the CVE report."
    required: false
    default: "true"

  # ---- SBOM (CycloneDX/SPDX) ----
  sbom-path:
    description: "Optional SBOM file to attest (CycloneDX XML/JSON or SPDX)."
    required: false
    default: ""
  sbom-format:
    description: "SBOM format (cyclonedx|spdx)."
    required: false
    default: "cyclonedx"
  sbom-media-type:
    description: "Override OCI media type; if empty inferred from format & extension."
    required: false
    default: ""

  # ---- OCI 1.1 Referrers ----
  use-oci-referrers:
    description: "If 'true', use OCI 1.1 referrers instead of tag-based metadata (recommended for GAR 'Attachments' tab)."
    required: false
    default: "true"

outputs:
  signed-ref:
    description: "Signed image reference (repo@digest)."
    value: ${{ steps.cosign-sign.outputs.signed_ref }}
  cve-attested:
    description: "Whether a CVE attestation was created."
    value: ${{ steps.cve-attest.outputs.attested }}
  sbom-attested:
    description: "Whether an SBOM attestation was created."
    value: ${{ steps.sbom-attest.outputs.attested }}

runs:
  using: "composite"
  steps:
    - name: Install Cosign
      uses: sigstore/cosign-installer@v4 
      with:
        cosign-release: 'v3.0.2'
        install-dir: $HOME/.cosign
        use-sudo: false

    # ---------- Sign ----------
    - name: Cosign sign (keyless OIDC)
      id: cosign-sign
      shell: bash
      env:
        COSIGN_OCI_11: ${{ inputs.use-oci-referrers }}
      run: |
        set -euo pipefail
        IMG="${{ inputs.image }}"
        [[ -z "$IMG" ]] && { echo "Input 'image' must not be empty"; exit 1; }

        # Build common flags
        FLAGS=()
        # OCI 1.1 Referrers mode
        if [[ "${{ inputs.use-oci-referrers }}" == "true" ]]; then
          FLAGS+=( "--registry-referrers-mode=oci-1-1" )
        fi
        # Rekor / transparency
        if [[ "${{ inputs.tlog-upload }}" == "false" ]]; then
          FLAGS+=( "--tlog-upload=false" )
        fi
        if [[ -n "${{ inputs.rekor-url }}" ]]; then
          FLAGS+=( "--rekor-url=${{ inputs.rekor-url }}" )
        fi
        # Helpful annotations (robust: -a "key=value")
        FLAGS+=( -a "repo=${GITHUB_REPOSITORY}" )
        FLAGS+=( -a "ref=${GITHUB_REF}" )
        FLAGS+=( -a "ref_name=${GITHUB_REF_NAME}" )
        FLAGS+=( -a "ref_type=${GITHUB_REF_TYPE}" )
        FLAGS+=( -a "sha=${GITHUB_SHA}" )
        FLAGS+=( -a "workflow=${GITHUB_WORKFLOW}" )
        FLAGS+=( -a "run_id=${GITHUB_RUN_ID}" )
        FLAGS+=( -a "run_attempt=${GITHUB_RUN_ATTEMPT}" )
        FLAGS+=( -a "run_url=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" )

        # User-provided extra annotations (newline-separated key=value)
        if [[ -n "${{ inputs.extra-annotations }}" ]]; then
          while IFS= read -r line; do
            [[ -z "$line" ]] && continue
            FLAGS+=( -a "$line" )
          done <<< "${{ inputs.extra-annotations }}"
        fi

        echo "Signing image: $IMG"
        if [[ "${{ inputs.recursive-sign }}" == "true" ]]; then
          echo "cosign sign --yes --recursive ${FLAGS[*]} '$IMG'"
          cosign sign --yes --recursive "${FLAGS[@]}" "$IMG"
        else
          cosign sign --yes "${FLAGS[@]}" "$IMG"
        fi

        echo "signed_ref=$IMG" >> "$GITHUB_OUTPUT"

    # ---------- CVE report attestation ----------
    - name: Cosign attest CVE report (optional)
      id: cve-attest
      if: ${{ inputs.cve-report != '' && inputs.attest-cve-report == 'true' }}
      shell: bash
      env:
        COSIGN_OCI_11: ${{ inputs.use-oci-referrers }}
      run: |
        set -euo pipefail
        IMG="${{ inputs.image }}"
        CVE="${{ inputs.cve-report }}"
        [[ ! -f "$CVE" ]] && { echo "CVE report file not found: $CVE"; exit 1; }
        
        AFLAGS=()
        if [[ "${{ inputs.use-oci-referrers }}" == "true" ]]; then
          AFLAGS+=( "--registry-referrers-mode=oci-1-1" )
        fi
        if [[ "${{ inputs.tlog-upload }}" == "false" ]]; then
        AFLAGS+=( "--tlog-upload=false" )
        fi
        if [[ -n "${{ inputs.rekor-url }}" ]]; then
        AFLAGS+=( "--rekor-url=${{ inputs.rekor-url }}" )
        fi
        
        echo "Attesting CVE report ($CVE) to $IMG"
        cosign attest --yes --type "vuln" --predicate "$CVE" "${AFLAGS[@]}" "$IMG"        
        echo "attested=true" >> "$GITHUB_OUTPUT"

    # ---------- SBOM attestation ----------

    - name: Cosign attest SBOM (optional)
      id: sbom-attest
      if: ${{ inputs.sbom-path != '' }}
      shell: bash
      env:
        COSIGN_OCI_11: ${{ inputs.use-oci-referrers }}
      run: |
        set -euo pipefail
        IMG="${{ inputs.image }}"
        SBOM="${{ inputs.sbom-path }}"
        FMT="${{ inputs.sbom-format }}"
               
        AFLAGS=()
        if [[ "${{ inputs.use-oci-referrers }}" == "true" ]]; then
          AFLAGS+=( "--registry-referrers-mode=oci-1-1" )
        fi
        if [[ "${{ inputs.tlog-upload }}" == "false" ]]; then
          AFLAGS+=( "--tlog-upload=false" )
        fi
        if [[ -n "${{ inputs.rekor-url }}" ]]; then
          AFLAGS+=( "--rekor-url=${{ inputs.rekor-url }}" )
        fi
        
        echo "Attesting SBOM (format: $FMT) to $IMG"
        cosign attest --yes --type "$FMT" --predicate "$SBOM" "${AFLAGS[@]}" "$IMG"
