# Unifits/unifits-github-actions/container-image-scan
name: "Container Image Scan"
description: "Generate Trivy HTML report and JSON CVE report for container image. Optionally fail the job on findings at or above a chosen severity."
branding:
  color: "green"
  icon: "shield"

inputs:
  image:
    description: "Image reference with digest (e.g., registry/repo@sha256:...)"
    required: true
  html-report:
    description: "Path for HTML report output"
    required: false
    default: "trivy-report.html"
  json-report:
    description: "Path for JSON report output"
    required: false
    default: "trivy-report.json"
  fail-on:
    description: "Whether the step should fail when vulnerabilities are found at or above the configured severity (true/false)."
    required: false
    default: "true"
  fail-on-severity:
    description: "Severity threshold at which a failure should be triggered (one of: LOW, MEDIUM, HIGH, CRITICAL)."
    required: false
    default: "CRITICAL"
  ignore-unfixed:
    description: "Ignore vulnerabilities that are not yet fixed (true/false)."
    required: false
    default: "true"

  # --- GCS Restore-only (fixer Key) ---
  gcs-bucket:
    description: "GCS Bucket für Trivy Cache"
    required: true
  gcs-path-prefix:
    description: "Prefix im Bucket (z. B. trivy-cache/)"
    required: false
    default: "trivy-cache/"
  trivy-cache-dir:
    description: "Lokaler Trivy Cache"
    required: false
    default: "~/.cache/trivy"
  fixed-cache-key:
    description: "Fixer Restore-Key, z. B. trivy-db-current oder trivy-db-YYYY-MM-DD"
    required: true

outputs:
  failed:
    description: "Boolean flag indicating if vulnerabilities at or above the fail-on-severity were found."
    value: ${{ steps.result.outputs.failed }}

runs:
  using: "composite"
  steps:

    # Restore ONLY: fixer Key
    - name: Restore Trivy cache (fixed key)
      uses: danySam/gcs-cache/restore@v1
      with:
        path: ${{ inputs.trivy-cache-dir }}
        key: ${{ inputs.fixed-cache-key }}
        gcs-bucket: ${{ steps.bkt.outputs.bucket }}
        gcs-path-prefix: ${{ inputs.gcs-path-prefix }}

    # Download Trivy HTML template
    - name: Download Trivy HTML Template
      shell: bash
      run: |
        set -euo pipefail
        curl --fail -sSL "https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl" -o html.tpl
        test -s html.tpl && echo "Template downloaded: $(wc -c < html.tpl) bytes"

    # Generate HTML Report using Trivy Action (human-readable)
    - name: Generate HTML Report using Trivy Action
      uses: aquasecurity/trivy-action@0.33.1
      with:
        cache: 'false'
        image-ref: ${{ inputs.image }}
        format: template
        template: "@html.tpl"
        output: ${{ inputs.html-report }}
        ignore-unfixed: false
        vuln-type: os,library
        severity: CRITICAL,HIGH
        scanners: vuln

    # Upload HTML Report as artifact
    - name: Upload HTML Report
      uses: actions/upload-artifact@v5
      with:
        name: trivy-html-report
        path: ${{ inputs.html-report }}

    # JSON CVE report (machine-readable). Exit code derived from fail-on.
    - name: Trivy JSON report
      id: trivy-json
      uses: aquasecurity/trivy-action@0.33.1
      with:
        cache: 'false'
        image-ref: ${{ inputs.image }}
        format: cosign-vuln
        output: ${{ inputs.json-report }}
        # If fail-on == 'true' => exit-code '1' (break the build on findings),
        # else exit-code '0' (always continue).
        exit-code: ${{ inputs.fail-on == 'true' && '1' || '0' }}
        ignore-unfixed: ${{ inputs.ignore-unfixed }}
        vuln-type: 'os,library'
        severity: ${{ inputs.fail-on-severity }}
        scanners: 'vuln'
      env:
        TRIVY_DISABLE_VEX_NOTICE: 'true'

    # Compute a 'failed' boolean output by checking if the scan step failed
    - name: Export result
      id: result
      shell: bash
      run: |
        # steps.trivy-json.outcome is 'success' or 'failure'
        OUTCOME="${{ steps.trivy-json.outcome }}"
        if [ "$OUTCOME" = "failure" ]; then
          echo "failed=true" >> "$GITHUB_OUTPUT"
        else
          echo "failed=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Save Maven cache to GCS (releases only)
      uses: danySam/gcs-cache/save@v1
      with:
        path: ${{ inputs.trivy-cache-dir }}
        key: ${{ inputs.fixed-cache-key }}
        gcs-bucket: ${{ steps.bkt.outputs.bucket }}
        gcs-path-prefix: ${{ inputs.gcs-path-prefix }}