
name: "Container Image Scan"
description: "Generate Trivy HTML (optional) and machine-readable vulnerability report (optional). Optionally fail on findings and generate an SBOM for attestation."
branding:
  color: "green"
  icon: "shield"

inputs:
  image:
    description: "Image reference with digest (e.g., registry/repo@sha256:...)"
    required: true

  # ---- Human-readable Report (HTML) ----
  html-enable:
    description: "If 'true', generate the Trivy HTML report"
    required: false
    default: "true"
  html-artifact-name:
    description: "Artifact name for the HTML report (default: trivy-html-report)"
    required: false
    default: "trivy-html-report"
  html-artifact-prefix:
    description: "Optional prefix prepended to the HTML artifact name (e.g., RUN_ID-image)"
    required: false
    default: ""

  # ---- Vulnerability report (optional & configurable) ----
  vuln-enable:
    description: "If 'true', generate a machine-readable vulnerability report"
    required: false
    default: "true"
  vuln-format:
    description: "Trivy report format (e.g., cosign-vuln, json, sarif)"
    required: false
    default: "cosign-vuln"

  # ---- Policy: Fail conditions ----
  fail-on:
    description: "Fail when vulnerabilities are found at/above 'fail-on-severity' (true/false)"
    required: false
    default: "true"
  fail-on-severity:
    description: "Severity threshold (one of: LOW, MEDIUM, HIGH, CRITICAL)"
    required: false
    default: "CRITICAL"
  ignore-unfixed:
    description: "Ignore vulnerabilities that are not yet fixed (true/false)"
    required: false
    default: "true"

  # ---- SBOM (optional) ----
  sbom-enable:
    description: "If 'true', generate an SBOM for the image"
    required: false
    default: "true"
  sbom-format:
    description: "SBOM output format for Trivy (one of: cyclonedx-json, spdx-json)"
    required: false
    default: "cyclonedx-json"
  sbom-artifact-name:
    description: "Artifact name for the SBOM (default: sbom)"
    required: false
    default: "sbom"
  sbom-artifact-prefix:
    description: "Optional prefix prepended to the SBOM artifact name (e.g., RUN_ID-image)"
    required: false
    default: ""

  # --- GCS Restore-only (fixed key) ---
  gcs-bucket:
    description: "GCS Bucket für Trivy Cache"
    required: true
  gcs-path-prefix:
    description: "Prefix im Bucket (z. B. trivy-cache)"
    required: false
    default: "trivy-cache"
  fixed-cache-key:
    description: "Fixer Restore-Key, z. B. trivy-db-current oder trivy-db-YYYY-MM-DD"
    required: true

outputs:
  failed:
    description: "Boolean flag indicating if vulnerabilities at/above fail-on-severity were found."
    value: ${{ steps.result.outputs.failed }}
  json-report-path:
    description: "Path of the generated vulnerability report (if vuln-enable == true)."
    value: ${{ steps.report-meta.outputs.json_path }}
  html-report-path:
    description: "Path of the generated Trivy HTML report (if html-enable == true)."
    value: ${{ steps.report-meta.outputs.html_path }}
  sbom-path:
    description: "Path of the generated SBOM (if sbom-enable == true)"
    value: ${{ steps.sbom-meta.outputs.path }}
  sbom-format:
    description: "SBOM format normalized for signing action (cyclonedx|spdx)"
    value: ${{ steps.sbom-meta.outputs.format }}

runs:
  using: "composite"
  steps:

    # Restore ONLY: fixer Key
    - name: Restore Trivy cache (fixed key)
      id: restore-cache
      uses: danySam/gcs-cache/restore@848b6287a9b0f9f7318bcb57b9f84a3e761acb29 # v1
      with:
        path: '${{ github.workspace }}/.cache/trivy'
        key: ${{ inputs.fixed-cache-key }}
        gcs-bucket: ${{ inputs.gcs-bucket }}
        gcs-path-prefix: ${{ inputs.gcs-path-prefix }}

    # Workaround - steps.restore-cache.outputs.cache-hit == 'false' funktioniert nicht
    - name: Mark restore as hit/miss
      id: restore-mark
      shell: bash
      run: |
        set -euo pipefail
        CACHE="${{ github.workspace }}/.cache/trivy"
        if [ -f "$CACHE/db/trivy.db" ] && [ -f "$CACHE/java-db/trivy-java.db" ]; then
          echo "hit=true" >> "$GITHUB_OUTPUT"
        else
          echo "hit=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Install Trivy
      uses: aquasecurity/setup-trivy@3fb12ec12f41e471780db15c232d5dd185dcb514 # v0.2.5
      with:
        version: v0.68.1

    # Download Trivy HTML template
    - name: Download Trivy HTML Template
      if: ${{ inputs.html-enable == 'true' }}
      shell: bash
      run: |
        set -euo pipefail
        curl --fail -sSL "https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl" -o html.tpl
        test -s html.tpl && echo "Template downloaded: $(wc -c < html.tpl) bytes"

    # Generate HTML Report using Trivy Action (human-readable)
    - name: Generate HTML Report using Trivy Action
      if: ${{ inputs.html-enable == 'true' }}
      uses: aquasecurity/trivy-action@c1824fd6edce30d7ab345a9989de00bbd46ef284 # 0.34.0
      with:
        cache: 'false'
        skip-setup-trivy: 'true'
        image-ref: ${{ inputs.image }}
        format: template
        template: "@html.tpl"
        output: trivy-report.html
        ignore-unfixed: false
        vuln-type: os,library
        severity: CRITICAL,HIGH
        scanners: vuln

    # Upload HTML Report as artifact (customizable name, overwrite to avoid 409)
    - name: Upload HTML Report
      if: ${{ inputs.html-enable == 'true' }}
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
      with:
        name: ${{ inputs.html-artifact-prefix != '' && format('{0}-{1}', inputs.html-artifact-prefix, inputs.html-artifact-name) || inputs.html-artifact-name }}
        path: trivy-report.html
        overwrite: true
        if-no-files-found: warn

    # Vulnerability report (machine-readable). Exit code derived from fail-on.
    - name: Vulnerability report (machine-readable)
      id: trivy-json
      if: ${{ inputs.vuln-enable == 'true' }}
      uses: aquasecurity/trivy-action@c1824fd6edce30d7ab345a9989de00bbd46ef284 # 0.34.0
      with:
        skip-setup-trivy: 'true'
        cache: 'false'
        image-ref: ${{ inputs.image }}
        format: ${{ inputs.vuln-format }}
        output: trivy-report.json
        exit-code: ${{ inputs.fail-on == 'true' && '1' || '0' }}
        ignore-unfixed: ${{ inputs.ignore-unfixed }}
        vuln-type: 'os,library'
        severity: ${{ inputs.fail-on-severity }}
        scanners: 'vuln'
      env:
        TRIVY_DISABLE_VEX_NOTICE: 'true'

    # Normalize report outputs (JSON/HTML) for downstream actions
    - name: Normalize report outputs
      id: report-meta
      shell: bash
      run: |
        set -euo pipefail
        JR="trivy-report.json"
        HR="trivy-report.html"
        if [[ "${{ inputs.vuln-enable }}" == "true" && -s "$JR" ]]; then
          echo "json_path=${JR}" >> "$GITHUB_OUTPUT"
        else
          echo "::notice::Vuln report disabled or not found: $JR"
          echo "json_path=${JR}" >> "$GITHUB_OUTPUT"
        fi
        if [[ "${{ inputs.html-enable }}" == "true" && -s "$HR" ]]; then
          echo "html_path=${HR}" >> "$GITHUB_OUTPUT"
        else
          echo "::notice::HTML report disabled or not found: $HR"
          echo "html_path=${HR}" >> "$GITHUB_OUTPUT"
        fi

    # Optional: SBOM generation (1) – erzeugen
    - name: Generate SBOM (optional)
      if: ${{ inputs.sbom-enable == 'true' }}
      uses: aquasecurity/trivy-action@c1824fd6edce30d7ab345a9989de00bbd46ef284 # 0.34.0
      with:
        skip-setup-trivy: 'true'
        cache: 'false'
        image-ref: ${{ inputs.image }}
        # Map Input -> Trivy:
        #   cyclonedx-json -> cyclonedx
        #   spdx-json      -> spdx-json
        format: ${{ inputs.sbom-format == 'spdx-json' && 'spdx-json' || 'cyclonedx' }}
        output: ${{ inputs.sbom-format == 'spdx-json' && 'sbom.spdx.json' || 'sbom.cdx.json' }}
      env:
        TRIVY_DISABLE_VEX_NOTICE: 'true'

    # Optional: SBOM generation (2) – Outputs normalisieren
    - name: Normalize SBOM outputs
      id: sbom-meta
      if: ${{ inputs.sbom-enable == 'true' }}
      shell: bash
      run: |
        set -euo pipefail
        OUT="${{ inputs.sbom-format == 'spdx-json' && 'sbom.spdx.json' || 'sbom.cdx.json' }}"
        [[ -s "$OUT" ]] || { echo "SBOM not found or empty: $OUT" >&2; exit 1; }
        echo "path=${OUT}" >> "$GITHUB_OUTPUT"
        case "${{ inputs.sbom-format }}" in
          cyclonedx-json) echo "format=cyclonedx" >> "$GITHUB_OUTPUT" ;;
          spdx-json)      echo "format=spdx"      >> "$GITHUB_OUTPUT" ;;
          *) echo "Unsupported sbom-format: ${{ inputs.sbom-format }}" >&2; exit 1 ;;
        esac
        echo "SBOM generated: $OUT ($(wc -c < "$OUT") bytes)"

    # Upload SBOM as artifact (customizable name, overwrite to avoid 409)
    - name: Upload SBOM Artifact
      if: ${{ inputs.sbom-enable == 'true' }}
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
      with:
        name: ${{ inputs.sbom-artifact-prefix != '' && format('{0}-{1}', inputs.sbom-artifact-prefix, inputs.sbom-artifact-name) || inputs.sbom-artifact-name }}
        path: ${{ steps.sbom-meta.outputs.path }}
        overwrite: true
        if-no-files-found: error

    # Compute a 'failed' boolean output
    - name: Export result
      id: result
      shell: bash
      run: |
        if [ "${{ inputs.vuln-enable }}" = "true" ] && [ "${{ steps.trivy-json.outcome }}" = "failure" ]; then
          echo "failed=true" >> "$GITHUB_OUTPUT"
        else
          echo "failed=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Save Trivy cache to GCS (only on cache miss)
      if: steps.restore-mark.outputs.hit == 'false'
      uses: danySam/gcs-cache/save@848b6287a9b0f9f7318bcb57b9f84a3e761acb29 # v1
      with:
        path: '${{ github.workspace }}/.cache/trivy'
        key: ${{ inputs.fixed-cache-key }}
        gcs-bucket: ${{ inputs.gcs-bucket }}
        gcs-path-prefix: ${{ inputs.gcs-path-prefix }}
