# Unifits/unifits-github-actions/maven-jib-build
name: "Maven Jib build & push"
description: "Runs Maven with the dockerize profile, pushes the image via Jib to GAR, and emits the image digest."
branding:
  color: "purple"
  icon: "play"

inputs:
  maven-profile:
    description: "Maven profile to use for dockerization."
    required: false
    default: "dockerize"
  digest-output-file:
    description: "Filename used by Jib to write the built image digest."
    required: false
    default: "${{ github.workspace }}/digest.txt"
  maven-goals:
    description: "Maven goals to execute (space-separated)."
    required: false
    default: "deploy"
  batch-mode:
    description: "Use Maven batch mode (true/false)."
    required: false
    default: "true"
  update-snapshots:
    description: "Pass --update-snapshots flag (true/false)."
    required: false
    default: "true"
  extra-args:
    description: "Optional additional Maven arguments appended to the command (e.g., \"-DskipTests -Drevision=1.2.3\")."
    required: false
    default: ""

outputs:
  digest:
    description: "Image digest (sha256:…) produced by Jib."
    value: ${{ steps.maven.outputs.digest }}

runs:
  using: "composite"
  steps:
    - name: Build with Maven (Jib push + capture digest)
      id: maven
      shell: bash
      run: |
        set -euo pipefail

        BM_FLAG=""
        if [[ "${{ inputs.batch-mode }}" == "true" ]]; then
          BM_FLAG="--batch-mode"
        fi

        US_FLAG=""
        if [[ "${{ inputs.update-snapshots }}" == "true" ]]; then
          US_FLAG="--update-snapshots"
        fi

        CMD=( mvn "-P${{ inputs.maven-profile }}" ${BM_FLAG} ${US_FLAG} ${{ inputs.maven-goals }} \
              "-Djib.outputPaths.digest=${{ inputs.digest-output-file }}" )

        if [[ -n "${{ inputs.extra-args }}" ]]; then
          # shellcheck disable=SC2206
          EXTRA=( ${{ inputs.extra-args }} )
          CMD+=( "${EXTRA[@]}" )
        fi

        echo "Running: ${CMD[*]}"
        "${CMD[@]}"

        DIGEST="$(cat "${{ inputs.digest-output-file }}")"
        echo "digest=${DIGEST}" >> "$GITHUB_OUTPUT"
        echo "Image Digest: ${DIGEST}"
