
name: "Cosign Sign & Attest"
description: "Sign an image and create attestations (Provenance + CVE Report)"
inputs:
  image:
    description: "Image reference with digest"
    required: true
  cve-report:
    description: "Path to CVE report JSON file"
    required: true
runs:
  using: "composite"
  steps:
    # ----------------- Image Signierung  ---------------------------------------------
    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.10.0

    - name: Cosign Sign (keyless by digest)
      env:
        COSIGN_EXPERIMENTAL: "true"
      run: |
        cosign sign --yes --keyless \
        ${{ inputs.image }}

    # Eigene Build-Provenance-Attestation
    - name: Generate Provenance Predicate
      run: |
        cat > provenance.json <<'JSON'
        {
          "_type": "https://slsa.dev/provenance/v1",
          "buildType": "https://github.com/actions/build",
          "builder": { "id": "https://github.com/actions" },
          "buildConfig": {
            "workflow": "${{ github.workflow }}",
            "runId": "${{ github.run_id }}",
            "repo": "${{ github.repository }}",
            "ref": "${{ github.ref }}",
            "sha": "${{ github.sha }}"
          },
          "materials": []
        }
        JSON

    - name: Cosign Attest (store in GAR)
      env:
        COSIGN_EXPERIMENTAL: "true"
      run: |
        cosign attest --yes \
          --predicate provenance.json  \
          --type slsaprovenance \
          ${{ inputs.image }}

    # CVE-Report als Attestation anhängen
    - name: Cosign Attest CVE Report (store in GAR)
      env:
        COSIGN_EXPERIMENTAL: "true"
      run: |
        cosign attest --yes \
          --predicate "${{ inputs.cve-report }}" \
          --type vuln \
          ${{ inputs.image }}


